# ___  ___  ___   _________  ___  _____ ______   ________  _________  _______         ___  ________  ________  ________      
#|\  \|\  \|\  \ |\___   ___\\  \|\   _ \  _   \|\   __  \|\___   ___\\  ___ \       |\  \|\   __  \|\   __  \|\   ____\     
#\ \  \\\  \ \  \\|___ \  \_\ \  \ \  \\\__\ \  \ \  \|\  \|___ \  \_\ \   __/|      \ \  \ \  \|\  \ \  \|\ /\ \  \___|_    
# \ \  \\\  \ \  \    \ \  \ \ \  \ \  \\|__| \  \ \   __  \   \ \  \ \ \  \_|/__  __ \ \  \ \  \\\  \ \   __  \ \_____  \   
#  \ \  \\\  \ \  \____\ \  \ \ \  \ \  \    \ \  \ \  \ \  \   \ \  \ \ \  \_|\ \|\  \\_\  \ \  \\\  \ \  \|\  \|____|\  \  
#   \ \_______\ \_______\ \__\ \ \__\ \__\    \ \__\ \__\ \__\   \ \__\ \ \_______\ \________\ \_______\ \_______\____\_\  \ 
#    \|_______|\|_______|\|__|  \|__|\|__|     \|__|\|__|\|__|    \|__|  \|_______|\|________|\|_______|\|_______|\_________\
               
#
# PLEASE READ!!!!! IMPORTANT!!!!!!
#
# Befor you report bugs -> plase check our docs website for error codes or installation videos!
# https://docs.ultimate-plugins.de
#
# Our discord: https://discord.ultimate-plugins.de
#
               
Advanced:

  BStats: true
 
  Console_Logs: false
  
  #for example: json, yml
  SavingFile: "yml"
  
  EventCancelByWorldGuard: false
                        
Plugin:

  Format_Money: "0.00"
  
  Format_Exp: "0.00"
  
  #Do not change if you not sure!
  Save_In: "plugins/UltimateJobs/data"
  
  Use_GUI: true
  
# .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------. 
#| .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. |
#| |   ______     | || |   _____      | || |      __      | || |     ______   | || |  _________   | || |  ____  ____  | || |     ____     | || |   _____      | || |  ________    | || |  _________   | || |  _______     | || |    _______   | |
#| |  |_   __ \   | || |  |_   _|     | || |     /  \     | || |   .' ___  |  | || | |_   ___  |  | || | |_   ||   _| | || |   .'    `.   | || |  |_   _|     | || | |_   ___ `.  | || | |_   ___  |  | || | |_   __ \    | || |   /  ___  |  | |
#| |    | |__) |  | || |    | |       | || |    / /\ \    | || |  / .'   \_|  | || |   | |_  \_|  | || |   | |__| |   | || |  /  .--.  \  | || |    | |       | || |   | |   `. \ | || |   | |_  \_|  | || |   | |__) |   | || |  |  (__ \_|  | |
#| |    |  ___/   | || |    | |   _   | || |   / ____ \   | || |  | |         | || |   |  _|  _   | || |   |  __  |   | || |  | |    | |  | || |    | |   _   | || |   | |    | | | || |   |  _|  _   | || |   |  __ /    | || |   '.___`-.   | |
#| |   _| |_      | || |   _| |__/ |  | || | _/ /    \ \_ | || |  \ `.___.'\  | || |  _| |___/ |  | || |  _| |  | |_  | || |  \  `--'  /  | || |   _| |__/ |  | || |  _| |___.' / | || |  _| |___/ |  | || |  _| |  \ \_  | || |  |`\____) |  | |
#| |  |_____|     | || |  |________|  | || ||____|  |____|| || |   `._____.'  | || | |_________|  | || | |____||____| | || |   `.____.'   | || |  |________|  | || | |________.'  | || | |_________|  | || | |____| |___| | || |  |_______.'  | |
#| |              | || |              | || |              | || |              | || |              | || |              | || |              | || |              | || |              | || |              | || |              | || |              | |
#| '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' |
# '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------' 

#
# The Placeholers can be found here: https://docs.ultimate-plugins.de
#

PlaceHolders:

  No_Job: "§cNo Job"

  No_Points: "§cNo Points"

  No_Exp: "§cNo Exp"

  No_Level: "§cNo Level"
  
  No_Quest: "§aAll Quests Completed"
  
# .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------. 
#| .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. |
#| |   _____      | || |  _________   | || | ____   ____  | || |  _________   | || |   _____      | || |    _______   | |
#| |  |_   _|     | || | |_   ___  |  | || ||_  _| |_  _| | || | |_   ___  |  | || |  |_   _|     | || |   /  ___  |  | |
#| |    | |       | || |   | |_  \_|  | || |  \ \   / /   | || |   | |_  \_|  | || |    | |       | || |  |  (__ \_|  | |
#| |    | |   _   | || |   |  _|  _   | || |   \ \ / /    | || |   |  _|  _   | || |    | |   _   | || |   '.___`-.   | |
#| |   _| |__/ |  | || |  _| |___/ |  | || |    \ ' /     | || |  _| |___/ |  | || |   _| |__/ |  | || |  |`\____) |  | |
#| |  |________|  | || | |_________|  | || |     \_/      | || | |_________|  | || |  |________|  | || |  |_______.'  | |
#| |              | || |              | || |              | || |              | || |              | || |              | |
#| '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' |
# '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'

Use_Levels: true

Options:
 
  Title: true
  
  Title_Config:
  
    First: "&8| &bLevelUP &8|"
      
    Second: "&7Level &4<level>"
 
  Message: true
  
  Message_Config:
    
    Type: "<prefix> &7You reached an new Level! &8[&4<level>&8]"
   
# .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------. 
#| .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. |
#| |  _______     | || |  _________   | || | _____  _____ | || |      __      | || |  _______     | || |  ________    | || |    _______   | |
#| | |_   __ \    | || | |_   ___  |  | || ||_   _||_   _|| || |     /  \     | || | |_   __ \    | || | |_   ___ `.  | || |   /  ___  |  | |
#| |   | |__) |   | || |   | |_  \_|  | || |  | | /\ | |  | || |    / /\ \    | || |   | |__) |   | || |   | |   `. \ | || |  |  (__ \_|  | |
#| |   |  __ /    | || |   |  _|  _   | || |  | |/  \| |  | || |   / ____ \   | || |   |  __ /    | || |   | |    | | | || |   '.___`-.   | |
#| |  _| |  \ \_  | || |  _| |___/ |  | || |  |   /\   |  | || | _/ /    \ \_ | || |  _| |  \ \_  | || |  _| |___.' / | || |  |`\____) |  | |
#| | |____| |___| | || | |_________|  | || |  |__/  \__|  | || ||____|  |____|| || | |____| |___| | || | |________.'  | || |  |_______.'  | |
#| |              | || |              | || |              | || |              | || |              | || |              | || |              | |
#| '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' |
# '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'

#
# PlaceHolders:
# <job> = current job
# <money> = the reward
# <exp> = the reward
# <job_exp> = the exp of the current job
# <job_need> = the needed exp for an levelup
# <job_level> = the level of the current job

#
# You want to display a different reward message for every job? 
#
# "JOB" means, every job has his own diffent message
# "PUBLIC" means, that every job has the same message
#
# NOTE:
#
# All examples of different job messages can be found here: -> https://github.com/Warsteiner37/UltimateJobs/wiki
#

RewardMode: "PUBLIC"

Options_Rewards:

  public:

    Message: false
  
    Message_Type: "&8[&a&l+&8] <job> &8| &7<money> Dollar &8- &7<exp> Exp &8| &7<job_exp>&8/&7<job_need> &8[&6<job_level>&8]"
  
    Actionbar: false
  
    Actionbar_Type: "&8[&a&l+&8] <job> &8| &7<money> Dollar &8- &7<exp> Exp &8| &7<job_exp>&8/&7<job_need> &8[&6<job_level>&8]"
  
    BossBar: true
  
    BossBarConfig:
  
      Message: "<job> &8| &7<money> Dollar &8- &7<exp> Exp &8| &7<job_exp>&8/&7<job_need> &8[&6<job_level>&8]"
    
      Color: "BLUE"
    
      Style: "SEGMENTED_20"
    
      #time in ticks = 20 ticks = 1 second
      Ticks: 45
      
  Miner:
  
    Type: "BOSSBAR"
    
    Message: "<job> &8| &7<money> Dollar &8- &7<exp> Exp &8| &7<job_exp>&8/&7<job_need> &8[&6<job_level>&8]"
    
    Color: "RED"
    
    Style: "SEGMENTED_20"
    
    #time in ticks = 20 ticks = 1 second
    Ticks: 45
    
  Lumberjack:
  
    Type: "MESSAGE"
    
    Message: "&8[&a&l+&8] <job> &8| &7<money> Dollar &8- &7<exp> Exp &8| &7<job_exp>&8/&7<job_need> &8[&6<job_level>&8]"
    
  Builder:
  
    Type: "ACTIONBAR"
    
    Message: " &7<money> Dollar &8- &7<exp> Exp &8| &7<job_exp>&8/&7<job_need> &8[&6<job_level>&8]"
 
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
 